version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./wallet_app/
    env_file: .env
    volumes:
      - static:/static/
      # - media:/media
    depends_on:
      - db

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      # - media:/media
    depends_on:
      - backend